name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./g++ Menu_v2_fonction.cpp menu_appel.h menu_fonction.cpp -o menu_v2.exe 
    - name: make
      run: ./menu_v2.exe
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
